[package]
name = "file-handle"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]  # Important for FFI

[dependencies]
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
